### ISSUE TITLE
Better exception handling for share_data script

### ISSUE THREAD

**Issue by mhchia** [ZKStats/mpc-demo-infra#33]
## What's wrong?
Now if an account has 0 balance, our script just fail with tons of messages. Error message is inside
```
...
thread 'main' panicked at examples/binance/binance_prover.rs:522:49:
index out of bounds: the len is 0 but the index is 0
...
```

## How to fix it?
We should have a way to detect what error occurred, e.g. check "index out of bounds: the len is 0 but the index is 0", etc. Or probably return a better error message in binance prover

**Comment by exfinen** [comment]
This is coming from
```rust
let commitment_id = recv_private_commitments[0];
```

**Comment by exfinen** [comment]
It seems like when there is not ETH free balance, this error occurs.

**Comment by exfinen** [comment]
Changed to exit if no ETH balance is found
